/* MEDI 계기 레퍼런스 라이브러리 — 제조사 진단 기능·세팅치·이상 판정값
 *
 * 목적: 현장에서 계기/밸브/계전기 이상이 의심될 때, 해당 계기의 자가진단 기능과
 * 판정 기준(제조사 문서 기준)을 바로 찾아 교차 확인할 수 있게 한다.
 *
 * 정직성 원칙:
 *  - verified: true  = 제조사 도메인 공식 문서(매뉴얼/기술노트/제품페이지) 발췌로 확인
 *  - verified: false = 2차 출처(미러 사이트 등)/업계 통설 — 적용 전 해당 기기 매뉴얼로 재확인
 *  - 수치는 문서에서 확인된 것만 기재. 미확인 수치는 "수치 미확인"으로 명시.
 *  - 판정값·기본값은 기기 버전/옵션에 따라 다름 — 최종 확인은 항상 해당 기기 세팅 시트.
 *
 * 브라우저(window.MEDI.vendorlib)와 Node(require) 양쪽 동작.
 */
(function (root, factory) {
  if (typeof module !== 'undefined' && module.exports) module.exports = factory();
  else { root.MEDI = root.MEDI || {}; root.MEDI.vendorlib = factory(); }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  // 카테고리 정의 (필터 칩 순서 그대로)
  const CATS = {
    pressure: { ko: '압력/차압', ico: '🔵' },
    temperature: { ko: '온도', ico: '🌡️' },
    flow: { ko: '유량', ico: '🌊' },
    valve: { ko: '밸브/포지셔너', ico: '🎚️' },
    vibration: { ko: '진동', ico: '📳' },
    electrical: { ko: '전기/계전기', ico: '⚡' },
    transformer: { ko: '변압기', ico: '🔌' },
    standard: { ko: '표준/공통', ico: '📐' },
  };

  // 항목 스키마: { cat, vendor, model, func, detects, signature, setting, ne107, medi, source, verified }
  const ITEMS = [
    // ══════════ 압력/차압 트랜스미터 ══════════
    {
      cat: 'pressure', vendor: 'Emerson (Rosemount)', model: '3051S (옵션 DA2)',
      func: 'SPM 통계공정감시 / 임펄스라인 막힘 검출 (Plugged Impulse Line)',
      detects: '임펄스라인 막힘·동결, 공정 이상(화염 불안정·캐비테이션 등) — 압력 노이즈 변화 기반',
      signature: '압력 신호의 평균·표준편차·변동계수(CV)를 상시 계산. Learning(기준선 학습, 기본 3분 — 3/5/10분 선택) → Verification(검증값이 기준선 평균 대비 3σ 초과 차이면 검증 지속) → Monitoring 순. 표준편차(또는 CV)가 기준선 대비 감도 임계(High/Medium/Low, 기본 Medium) 초과 변화 시 경보. DP 유량은 CV 모드, 레벨/압력은 Stdev&Mean 모드 권장. 감도별 % 기본값 수치 미확인.',
      setting: 'Learn/Monitor Period(기본 3분), Detection Sensitivity(H/M/L/Custom), 진단 모드, 경보 방식(HART/아날로그)',
      ne107: '-',
      medi: '설비 상세 → 계기 건전성: 1차 차분 σ 붕괴 + 평균 유지 시그니처(동일 원리)로 자동 검출',
      source: 'Emerson 기술노트 (Plugged Impulse Line Detection, 3051S Advanced Diagnostics) · 매뉴얼 §7',
      verified: true,
    },
    {
      cat: 'pressure', vendor: 'Emerson (Rosemount)', model: '3051S / 3051',
      func: 'Power Advisory / 루프 건전성 진단',
      detects: '전기 루프 열화 — 단자 부식, 하우징 침수, 불안정 전원, 배선 문제',
      signature: '루프 특성화(Loop Characterization)로 단자 전압·저항 기준선을 캡처, 이후 단자 전압이 기준선 대비 편차 한계 초과 시 경보 — 편차 한계 기본 1.5 V.',
      setting: 'Loop Characterization 실행, Terminal Voltage Deviation Limit(기본 1.5 V), 경보 동작',
      ne107: '-',
      medi: '루프 문제로 신호가 튀면 계기 건전성 진단이 노이즈 폭증(결선/EMI)으로 검출',
      source: 'Emerson Loop Integrity Diagnostic 플라이어 · 3051S 매뉴얼 §7',
      verified: true,
    },
    {
      cat: 'pressure', vendor: 'Yokogawa', model: 'EJX / EJA-E (옵션 /DG6)',
      func: 'ILBD (임펄스라인 막힘 진단)',
      detects: '임펄스라인 막힘 — 고압측/저압측/양측/편측 4가지 모드 구분',
      signature: 'DPharp 멀티센싱(차압+양측 정압 동시 측정)으로 압력 요동 통계 분석. 블록킹 팩터 BlkF(-1~+1): +1 접근=고압측 막힘, -1 접근=저압측 막힘. 양측 막힘은 차압 요동비 Ratio fDP=√(fDP/Ref fDP)로 검출 — 매뉴얼 기재 임계 예: Lim fDPmax 1.50(High)/3.00(Medium), Lim fDPmin 0.40/0.30/0.20. 진단 주기(Diag Period) 기본 180초. 기준 요동 유효 하한 Ref Lim fDPmin=7.0E-10.',
      setting: 'Diag Period(기본 180s), Lim BlkFmax/min(기본값 미확인), Lim fDPmax/min, 정상운전 기준값(Ref fDP 등) 채취, 경보 출력 할당',
      ne107: 'HART 7 기종 NE107 상태정보 지원',
      medi: '계기 건전성 진단 impulse_plug 검출과 동일 원리 — 검출 시 벤더 진단으로 교차 확인',
      source: 'Yokogawa TI01C25A31-01E · IM01C25T01-06EN §4.2-4.3 · 공식 Application Note',
      verified: true,
    },
    {
      cat: 'pressure', vendor: 'Yokogawa', model: 'EJX (옵션 /DG6)',
      func: 'Heat Trace Monitoring (플랜지 온도 진단)',
      detects: '임펄스라인 보온(스팀/전기 히트트레이싱) 이상, 동절기 동결 위험',
      signature: '캡슐 온도와 앰프 온도로부터 플랜지 온도를 추정해 보온 건전성 감시 — 설정 범위 이탈 시 경보. 임계 기본값 수치 미확인.',
      setting: '플랜지 온도 상/하한 경보',
      ne107: 'HART 7 기종 NE107 지원',
      medi: '동절기에 압력 태그 노이즈가 서서히 죽으면 동결 진행 의심 — 계기 건전성 진단과 병행',
      source: 'Yokogawa 기술보고 (EJX Advanced Diagnostic Functions)',
      verified: true,
    },
    {
      cat: 'pressure', vendor: 'ABB', model: '266 / 2600T 시리즈',
      func: 'PILD (임펄스라인 막힘 검출)',
      detects: '임펄스라인 막힘 (편측/양측) — 측정값에 영향이 나타나기 전 사전 경고',
      signature: '공정 배경 노이즈의 주파수 스펙트럼을 정상운전 기준선과 비교. 정상 시 양측 라인의 노이즈가 차압에서 상쇄되지만, 편측 막힘 시 상쇄가 깨져 노이즈 증가, 양측 막힘 시 노이즈 감쇠 — 이 패턴으로 구분 검출. 임계 수치 미확인.',
      setting: '경보 출력 구성(HART/PA/FF): 통신 경고, Alarm current 구동, 상태 BAD 설정',
      ne107: 'F/M/S/C 아이콘 + 문제 부위 표시',
      medi: '계기 건전성 진단 impulse_plug와 동일 원리',
      source: 'ABB TD/P-SERIES_PILD-EN · 266 FF 매뉴얼',
      verified: true,
    },
    {
      cat: 'pressure', vendor: 'Endress+Hauser', model: 'Deltabar PMD75B/78B · Cerabar PMC71B/PMP71B',
      func: 'Heartbeat Technology (Verification + SSD + Loop/Process 진단)',
      detects: '임펄스라인 막힘(노이즈 감쇠), 루프 전압 이상, 공정 창 이탈, 기기 자체 고장',
      signature: 'Statistical Sensor Diagnostics(SSD) 위저드: DP 센서 압력 요동 스펙트럼을 통계 분석해 기준선 대비 노이즈 유의 감소 시 막힘 경보. Heartbeat Verification: 공정 무중단 자동 검증 시퀀스 + 리포트 — 4–20 mA 출력 시험 커버리지(TTC) >99% 기재. 개별 임계 기본값 수치 미확인.',
      setting: 'Heartbeat Verification 위저드, SSD 기준선 학습·감도, Process window(min/max), Loop diagnostics, 진단 이벤트별 NE107 재할당',
      ne107: 'F/C/S/M + 평문 오류코드',
      medi: '계기 건전성 진단 impulse_plug와 동일 원리 — Heartbeat 리포트로 교차 확인',
      source: 'E+H SD02525P (Heartbeat Special Documentation) · 공식 제품페이지',
      verified: true,
    },
    {
      cat: 'pressure', vendor: 'Honeywell', model: 'SmartLine ST800/STD800 (PILD 옵션)',
      func: 'PILD (임펄스라인 막힘 검출, 통계 모델·PILD factor)',
      detects: '임펄스라인 막힘 — 편측/양측(DP)',
      signature: '정상운전 노이즈 패턴 기준선을 통계 모델로 상시 비교 — Training(학습) 모드에서 PILD factor 산출, Monitoring 모드에서 감시. 검출 시 non-critical 진단 표시. 임계 기본값 수치 미확인.',
      setting: 'PILD Enable, 모드(Training/Monitoring), Up/Down/Both Limit(Monitoring 모드에서만 변경)',
      ne107: 'NE107 Extended Diagnostics 지원',
      medi: '계기 건전성 진단 impulse_plug와 동일 원리',
      source: 'Honeywell 34-ST-25-38 · 34-ST-25-35 §5.6',
      verified: true,
    },
    {
      cat: 'pressure', vendor: 'Siemens', model: 'SITRANS P320/P420',
      func: 'NE107 진단 — 한계 감시·이벤트 카운터·트렌드 로그',
      detects: '공정값 한계 초과 반복, 센서/전자부 고장, 포화, 구성 변경 이력',
      signature: '감시값이 설정 한계를 초과한 횟수를 계수, 임계 도달 시 Maintenance alarm(예: 진단 A0 "Event counter overruns above threshold"). P420은 트렌드 로그 최대 1,500점 기기 내 저장 + 파라미터 변경 로그. 개별 임계 기본값 수치 미확인.',
      setting: 'Monitored value, Upper/Lower limit, 이벤트 카운터 임계·리셋, 트렌드 기록',
      ne107: 'NE107 준수 (이벤트 카운터 초과 = M)',
      medi: '한계 접근은 이 앱의 설계한계 알람과 동일 개념 — 기기 내 이력과 히스토리안 이력 대조 가능',
      source: 'Siemens P320/P420 Service Manual (A5E44914141)',
      verified: true,
    },
    {
      cat: 'pressure', vendor: 'Siemens', model: 'SITRANS P DS III',
      func: 'HART 진단 — 교정/서비스 타이머·min/max 포인터·한계 감시',
      detects: '교정/정비 주기 초과, 측정값 극값 이력, 한계 초과',
      signature: '교정/서비스 타이머: 1차 시한 경과 시 경고, 2차 시한 경과 시 진단 경보 + 고장 전류 출력. min/max 슬레이브 포인터로 극값 이력 확인. 구체 기본값 수치 미확인.',
      setting: '타이머 시한(1차/2차), 한계 감시, 포인터 리셋, 고장 전류 동작',
      ne107: '-',
      medi: '-',
      source: 'Siemens DS III HART 매뉴얼 (A5E00047092)',
      verified: true,
    },
    {
      cat: 'pressure', vendor: 'Azbil', model: 'AT9000 (GTX 시리즈)',
      func: '고급 진단 — 압력 주파수 지표·표준편차 진단',
      detects: '임펄스라인(연결배관) 막힘, 기기 고장(자기진단)',
      signature: '압력 신호의 주파수 성분 지표(pressure frequency index)와 표준편차 진단으로 연결배관 막힘 검출. 자기진단은 고장 발생 후 5분 이내 검출, HART Diagnostic Status/Status Records로 확인. 임계 기본값 수치 미확인.',
      setting: 'HART Diagnostic 메뉴에서 상태/기록 확인, 진단 파라미터는 매뉴얼 참조',
      ne107: '-',
      medi: '계기 건전성 진단 impulse_plug와 동일 원리',
      source: 'Azbil CM2-GTX100-2005 · CM2-GTX000-2002',
      verified: true,
    },

    // ══════════ 온도 트랜스미터 ══════════
    {
      cat: 'temperature', vendor: 'Emerson (Rosemount)', model: '3144P',
      func: 'Sensor Drift Alert (센서 드리프트 경보)',
      detects: '이중 센서 간 측정 편차 증가 — RTD/TC 드리프트, 센서 열화',
      signature: '동일 지점의 Sensor 1·2 온도차 |S1−S2|가 사용자 정의 한계 초과 시 HART 경고 또는 아날로그 알람. 공장 기본값: 온도차 한계 3°C (5.4°F), 댐핑 5초.',
      setting: '드리프트 한계 온도차(기본 3°C), 경고/알람 모드, 댐핑 시간',
      ne107: '-',
      medi: '계기 건전성 진단의 단독 드리프트 검출(단일 센서 근사) — 이중 센서가 있으면 벤더 기능이 더 정확',
      source: 'Emerson 3144P Product Data Sheet',
      verified: true,
    },
    {
      cat: 'temperature', vendor: 'Emerson (Rosemount)', model: '3144P',
      func: 'Hot Backup + 열전대 열화 진단',
      detects: '1차 센서 고장(단선), 열전대 노화·배선 열화',
      signature: 'Hot Backup: Sensor 1 고장 시 자동으로 Sensor 2로 무충격 전환 + 고장 진단 정보 제공. TC 열화 진단: 열전대 루프 저항을 감시해 저항 증가로 고장 전 조기 경고. 전환 임계·저항 한계 수치 미확인.',
      setting: 'Hot Backup 활성화, 복귀 방식, TC 저항 감시 활성화',
      ne107: '-',
      medi: '센서 단선은 계기 건전성 stuck/노이즈 진단으로도 부분 검출',
      source: 'Emerson 3144P Product Data Sheet',
      verified: true,
    },
    {
      cat: 'temperature', vendor: 'Yokogawa', model: 'YTA610 / YTA710',
      func: '센서 백업 + 센서 드리프트 감지',
      detects: '센서 단선/고장, 이중 센서 드리프트, (YTA710) TC/RTD 단락·단자 부식',
      signature: '드리프트 감지(2입력 모델): S1−S2 온도차가 임계 초과 시 Sensor Drift 알람. 백업 운전 중 S1 고장 시 AL.23 "Backup S1 Fail" 출력 후 S2로 계속 측정, 양쪽 고장 시 Sensor Burnout. YTA710 추가: TC 단락(저항이 고객 정의 임계 미만), RTD 단락(입력 타입별 사전 임계), RTD 부식 감지 — NE89 대응. 드리프트 임계 기본값 수치 미확인.',
      setting: '드리프트 임계 온도차, 백업 활성화, (YTA710) TC 단락 저항 임계',
      ne107: 'NE89 대응 확인',
      medi: '계기 건전성 진단 drift 검출과 교차 확인',
      source: 'Yokogawa GS01C50G01-01EN',
      verified: true,
    },
    {
      cat: 'temperature', vendor: 'ABB', model: 'TTH300',
      func: '센서 드리프트 감시 + 센서 이중화',
      detects: '이중 센서 간 편차(드리프트), 단일 센서 고장',
      signature: '설정된 "최대 허용 센서 편차" 초과 시 진단 이벤트. 이중화 모드는 두 센서 평균으로 출력, 한쪽 고장 시 측정 연속성 유지. 편차 기본값 수치 미확인. 주의: 드리프트 감시 설정 전 채널 1 기준 센서 조정 선행 필요.',
      setting: '최대 허용 센서 편차, 이중화 모드 — DTM(DAT200)/EDD/FDI로 설정',
      ne107: 'NE107·NE89 준수 명시',
      medi: '계기 건전성 진단 drift 검출과 교차 확인',
      source: 'ABB TTH300 Operating Instruction (2차 출처 경유 — 기기 매뉴얼 재확인 권장)',
      verified: false,
    },
    {
      cat: 'temperature', vendor: 'Endress+Hauser', model: 'iTEMP TMT82',
      func: '드리프트/편차 감시 + 센서 백업 + 부식 감지',
      detects: '이중 센서 드리프트, 센서 케이블 부식, 단선/단락/오배선',
      signature: 'S1−S2 편차가 설정 한계 초과(Out band=드리프트 모드) 또는 미만(In band 모드) 시 경고/알람. 4선식 RTD/TC 부식 감지: 도체 저항이 타당 한계 초과 시 HART 경고. set point 기본값 수치 미확인.',
      setting: 'Drift/difference mode(Out/In band), set point, alarm delay (Setup→Advanced setup→Sensors), 진단 카테고리 할당, 센서 백업 병용',
      ne107: 'NE107 지원 (SIL2/SC3)',
      medi: '계기 건전성 진단 drift 검출과 교차 확인',
      source: 'E+H BA01028T (TMT82 Operating Instructions)',
      verified: true,
    },
    {
      cat: 'temperature', vendor: 'Endress+Hauser', model: 'iTEMP TMT162',
      func: '센서 드리프트 감지 + 부식 감지',
      detects: '이중 센서 드리프트, TC/4선 RTD 연결부 부식',
      signature: 'S1−S2가 지정값 이탈 시 진단 코드 044 "Sensor drift" 경고/알람. 부식 감지: 배선 저항이 타당 한계 초과 시 측정 왜곡 전에 경고 — 진단 코드 042 "Sensor n corroded" (비활성 시 알람 한계 도달 후 F-041만). 임계 수치 미확인.',
      setting: 'Sensor Drift Monitoring Configuration(AdvDiagnostic), 부식 감지 활성화, 이벤트 카테고리',
      ne107: '진단 이벤트 카테고리 구성 가능',
      medi: '계기 건전성 진단 drift 검출과 교차 확인',
      source: 'E+H BA01801T (TMT162 Operating Instructions)',
      verified: true,
    },
    {
      cat: 'temperature', vendor: 'WIKA', model: 'T32.xS (TIF50/52 포함)',
      func: '센서 드리프트 감지 + 이중 센서 리던던시',
      detects: '이중 센서 드리프트, 센서 단선·배선 고장',
      signature: 'Sensor 1·2 온도차가 사용자 선택값 초과 시 오류 신호. 리던던시 구성 시 센서 고장에서 정상 센서로 자동 전환. 기본값 수치 미확인.',
      setting: '드리프트 판정 온도차, 리던던시 모드 — HART 범용 도구로 설정',
      ne107: 'NAMUR 권고 준수 상태 정보',
      medi: '계기 건전성 진단 drift 검출과 교차 확인',
      source: 'WIKA T32.xS 공식 제품페이지',
      verified: true,
    },
    {
      cat: 'temperature', vendor: 'Siemens', model: 'SITRANS TH400',
      func: '센서 리던던시 + 드리프트 감지',
      detects: '1차 센서 고장, 이중 센서 드리프트',
      signature: '이중 입력으로 차이/평균/리던던시 측정. 리던던시 모드: 1차 고장 시 2차로 자동 전환. 센서 간 편차가 사전 정의 한계 초과 시 경보. 한계 기본값 수치 미확인.',
      setting: '측정 모드, 드리프트 한계 — SIMATIC PDM(PA)/AMS(FF)',
      ne107: '-',
      medi: '계기 건전성 진단 drift 검출과 교차 확인',
      source: 'Siemens TH400 Operating Instructions (A5E01018688)',
      verified: true,
    },

    // ══════════ 밸브 / 포지셔너 ══════════
    {
      cat: 'valve', vendor: 'Emerson (Fisher)', model: 'FIELDVUE DVC6200 + ValveLink',
      func: 'Travel Deviation Alert (트래블 편차 경보)',
      detects: '스틱션, 공기 공급 부족, 액추에이터 출력 부족, 밸브 고착 — 지시-실개도 불일치',
      signature: '트래블 목표와 실제 트래블 차이가 Alert Point를 Deviation Time보다 오래 초과하면 경보. 공장 기본값: Alert Point 5%, Deviation Time 9.99초.',
      setting: 'Travel Deviation Alert Point(%), Deviation Time(초), Alert Deadband — ValveLink Travel Alerts 탭',
      ne107: '- (PlantWeb Alert 체계)',
      medi: '이 앱의 OP-실개도 편차(pos_gap) 지표와 동일 개념 — 히스토리안으로 상시 감시',
      source: 'Emerson DVC6200 HW2 Instruction Manual',
      verified: true,
    },
    {
      cat: 'valve', vendor: 'Emerson (Fisher)', model: 'FIELDVUE DVC6200 + ValveLink',
      func: 'Supply Pressure Lo Alert (공급압 저하 경보)',
      detects: '계장 공기 공급압 저하 — 레귤레이터/배관 문제, 스트로크 지연의 원인',
      signature: '내장 압력 센서로 공급압 감시, 설정 포인트 미만이면 경보. 기본값 수치 미확인 — 권장 원칙: 스프링-다이어프램은 상부 벤치세트 압력 직하, 피스톤은 구동 최소 압력.',
      setting: 'Supply Pressure Lo Alert Point — ValveLink Pressure Alerts 탭',
      ne107: '-',
      medi: '이 앱의 차단밸브 구동 공기압(air_supply) 감시와 동일 개념',
      source: 'Emerson DVC6200 HW2 Instruction Manual',
      verified: true,
    },
    {
      cat: 'valve', vendor: 'Emerson (Fisher)', model: 'FIELDVUE DVC6200 + ValveLink',
      func: 'Cycle Counter / Travel Accumulator',
      detects: '패킹·벨로우즈·액추에이터 씰 등 마모성 부품의 누적 사용량 초과',
      signature: 'Cycle Counter: 방향 전환 횟수 누적, Travel Accumulator: 총 트래블 이동량(%) 누적 — 설정 한계 초과 시 경보. 공장 기본 Alert Point 각 1,000,000, 판정 Deadband 예시 10%. (2차 출처 인용 — 기기 매뉴얼 재확인)',
      setting: 'Alert Point, Deadband(%) — 패킹 수명 기준 설정, 정비 후 리셋',
      ne107: '-',
      medi: '이 앱의 누적 이동량·반전 카운트/일 지표와 직접 대응 — 히스토리안 개도 신호로 동일 계산',
      source: 'DVC6200 매뉴얼 (2차 출처 경유)',
      verified: false,
    },
    {
      cat: 'valve', vendor: 'Emerson (Fisher)', model: 'FIELDVUE DVC6200 SIS',
      func: 'PST (부분행정시험)',
      detects: '긴급차단밸브 고착, 마찰 증가, 액추에이터 이상 — 전행정 없이 주기 검증',
      signature: '설정 트래블만큼 램프 이동 후 복귀하며 압력-트래블 거동 분석. 문서 기본값: Travel Target 10%(High Cv 버전 20%), Ramp Rate 0.25%/s, Pressure Threshold는 PST Calibration 시 자동 설정(임계 위반 시 시험 중단).',
      setting: 'Travel Target(%), Ramp Rate(%/s), Pressure Threshold, 시험 주기(Auto PST)',
      ne107: '-',
      medi: '이 앱의 차단밸브 스트로크 시간 추세 감시가 PST 실무의 히스토리안 근사',
      source: 'Emerson DVC6200 SIS PST Calibration Supplement',
      verified: true,
    },
    {
      cat: 'valve', vendor: 'Valmet (Neles)', model: 'ND9000 (H/F/P)',
      func: 'Load Factor(부하율) + 스틱션 온라인 진단',
      detects: '액추에이터 부하 증가(스프링 이상·과부하), 밸브 마찰/스틱션 증가·감소(패킹 풀림)',
      signature: '성능 진단이 load와 stiction 평균값을 24시간 간격으로 low/high 경고 한계와 비교. 온라인 알람: 스틱션이 온라인 한계를 지정 횟수(STICTION_LATCH_NBR) 벗어나면 알람. Valve Online Signature로 운전 중 마찰 온라인 표시. 한계 기본값 수치 미확인.',
      setting: 'load/stiction low·high 한계, 온라인 알람 한계·래치 횟수, 총 트래블·반전 한계',
      ne107: '-',
      medi: '이 앱의 스틱션 정량화(PV-OP 타원, %)와 교차 확인 — 3% 초과 시 정비 검토 통례',
      source: 'Valmet ND9000F User\'s Guide',
      verified: true,
    },
    {
      cat: 'valve', vendor: 'SAMSON', model: 'TROVIS 3730-3 + EXPERTplus',
      func: 'EXPERTplus 내장 밸브 진단 (데드밴드·스텝응답·구동신호)',
      detects: '패킹 마찰 증가(데드밴드 확대), 응답 지연, 제로점 이동(시트/플러그 마모), 공기 누설',
      signature: '진단이 포지셔너에 완전 내장 — 온라인 관찰 모드로 공정 무중단 수집·분석 후 분류된 상태 메시지 생성. Dead band 테스트(마찰 히스테리시스 기반), Step response 테스트(FST: overshoot·dead time·T98, PST: T63·T98 등), Drive signal 정상상태 진단. 판정 한계 기본값 수치 미확인.',
      setting: '기준(reference) 테스트 선행, 테스트별 활성화·한계, TROVIS-VIEW/DTM 조회',
      ne107: 'NE107 준거 상태 메시지 명시',
      medi: '데드밴드 확대는 이 앱의 스틱션 정량화·진동 검출로 원격 감시',
      source: 'SAMSON EB 8484-3 (e83893)',
      verified: true,
    },
    {
      cat: 'valve', vendor: 'Flowserve', model: 'Logix 3400MD/3200MD + ValveSight',
      func: '마찰·압력 진단 + 사이클/트래블 누적 카운터',
      detects: '밸브 마찰 증가, 공급/액추에이터 압력 손실, 마모 부품 누적 사용량',
      signature: '마찰 캘리브레이션으로 기준선 확보, 고급 모델은 3개 압력 센서로 압력 손실 감지 + 밸브 시그니처 진단. Travel Accumulator(주행계 개념 — 스트로크 단위 누적), Cycle Counter(반전 횟수). 경보 한계 기본값 수치 미확인.',
      setting: '스트로크 길이·단위, travel dead-band, 마찰/압력 캘리브레이션, 누적 한계 경보',
      ne107: '-',
      medi: '이 앱의 누적 이동량·반전 카운트와 동일 개념',
      source: 'Flowserve Logix 3400MD 공식 제품페이지',
      verified: true,
    },
    {
      cat: 'valve', vendor: 'Siemens', model: 'SIPART PS2',
      func: '스트로크/방향전환 카운터 + 데드밴드 자동 적응',
      detects: '스틱션 증가, 공기 누설, 루프 진동, 마모 부품 누적 사용량',
      signature: '진단값 STRKS(100% 환산 총 스트로크)와 CHDIR(방향 전환 횟수)를 파라미터 50/51 한계와 비교 — 오류 코드 4(스트로크 한계)/5(방향전환 한계)/8(데드존 적응 한계). 데드밴드 DEBA=Auto 시 스틱션·진동 감지되면 0.1% 단위로 자동 확대, 개선 시 축소 — 적응 이력 자체가 스틱션 지표. 한계 기본값 수치 미확인.',
      setting: '파라미터 50(스트로크 한계)/51(방향전환 한계), DEBA(Auto/고정)',
      ne107: '-',
      medi: '데드밴드 확대·진동은 이 앱의 ACF 진동 검출·스틱션 정량화와 교차 확인',
      source: 'Siemens SIPART PS2 파라미터/진단 문서 (support.industry.siemens.com)',
      verified: true,
    },
    {
      cat: 'valve', vendor: 'Flowserve', model: 'Limitorque MX/QX (전동 액추에이터)',
      func: '토크 프로파일 + 모터 상태 진단',
      detects: '밸브 토크 요구 증가(고착·마모), 모터 이상(전압/전류/온도), 구동계 고장 징후',
      signature: '최근 스트로크 토크를 기준선과 비교. 모터 전압·전류·온도, 총 회전수, 접촉기 동작 횟수, 스트로크 시간 로그. FDA(주파수 영역 분석): 토크/위치/속도를 FFT 변환해 고장 임박 부품 지목. 판정 한계 수치 미확인. (2차 출처 인용 — 기기 매뉴얼 재확인)',
      setting: '토크 기준선(시운전 시), 토크·스트로크 시간 한계, ValveSight 연동',
      ne107: '-',
      medi: '이 앱의 차단밸브 스트로크 시간 추세와 동일 개념 — 전동밸브는 토크·전류 태그 수집 권장',
      source: 'Limitorque MX/QX 문서 (2차 출처 경유)',
      verified: false,
    },

    // ══════════ 유량계 ══════════
    {
      cat: 'flow', vendor: 'Emerson (Micro Motion)', model: '코리올리 유량계 — SMV',
      func: 'Smart Meter Verification (인시투 계기 검증)',
      detects: '튜브 부식·침식·코팅·과압 변형, 드라이브/픽오프 코일·RTD 열화, 전자부 이상',
      signature: '코리올리 튜브의 기계적 강성(stiffness)은 유량 교정계수와 직접 상관 — 공장 기준 강성 대비 현재 강성의 편차가 사양 한계를 벗어나면 Fail. 공정 중단 없이 실행. 화이트페이퍼 사례: 강성 4% 감소가 약 0.3 g/cc 밀도 오차 유발. Fail 판정 공식 한계 %값 수치 미확인.',
      setting: '실행 방식(수동/스케줄), 결과 알람 연동, 베이스라인 재설정',
      ne107: '-',
      medi: '유량-전류/차압 관계 잔차(회귀 패턴)가 흐르면 계기 열화 vs 공정 변화 감별에 SMV로 교차 확인',
      source: 'Emerson Micro Motion SMV 공식 페이지 · 화이트페이퍼(강성-부식 추적)',
      verified: true,
    },
    {
      cat: 'flow', vendor: 'Endress+Hauser', model: 'Proline Promass 300/500 (코리올리)',
      func: 'Heartbeat Verification (추적성 검증)',
      detects: '센서 무결성(HBSI), 신호 단선·절연 불량·접점 부식, 센서 내 습기, 튜브 손상, 전자부 드리프트',
      signature: '공장 교정 시 영구 저장된 기준값 대비 테스트 그룹별 검사 — 전 그룹 합격 시 "Passed", 하나라도 허용 오차 이탈 시 "Failed". 이중화 기준이 상호 교차검증. 총 시험 커버리지(TTC) >94%, TÜV SÜD 인증(ISO 9001 §7.1.5.2a 추적성) — 습식 교정 주기 연장 근거로 사용 가능. 리포트는 변조 방지 PDF.',
      setting: '검증 실행(디스플레이/웹서버/DCS 원격), 검증 주기, Heartbeat Monitoring 트렌드(HBSI 등) 알람 한계',
      ne107: 'F/C/S/M 분류 지원',
      medi: '유량 태그 품질 의심 시 Heartbeat 리포트로 계기 건전성 확정 — 계기 문제 배제 후 공정 진단',
      source: 'E+H SD01643D (Heartbeat Special Doc) · 공식 기술페이지',
      verified: true,
    },
    {
      cat: 'flow', vendor: 'Endress+Hauser', model: 'Proline Promag 300/400/500 (전자식)',
      func: 'Heartbeat Verification',
      detects: '여자 코일 저항 변화, 전극·EPD 케이블 이상, 자기장 세기 변화(기계적 결함), 공급 전압 이상',
      signature: 'Promass와 동일 — 공장 기준값 대비 그룹별 Passed/Failed. HBSI가 자기장 세기 변화를 상시 감시해 정확도에 영향 주는 기계적 결함 검출. 개별 한계는 기기 내 저장 — 공개 수치 미확인.',
      setting: '검증 주기, 코일 저항·HBSI 트렌드 알람 한계',
      ne107: 'F/C/S/M 분류 지원',
      medi: '유량 태그 노이즈/드리프트 의심 시 교차 확인',
      source: 'E+H SD01847D · Promag Heartbeat 공식 페이지',
      verified: true,
    },
    {
      cat: 'flow', vendor: 'Yokogawa', model: 'digitalYEWFLO / VY (와류식)',
      func: 'SSP 자기진단 (Spectral Signal Processing)',
      detects: '셰더바 주변 막힘, 배관 고진동, 유량 과도 변동(이상 유동)',
      signature: '두 압전 소자의 편광 배치로 진동 영향 상쇄 + SSP가 와류 파형을 스펙트럼 분해해 노이즈/신호 분리 — 진동·막힘·유동 이상 시 진단 알람. 임계 수치 미확인.',
      setting: '자기진단 알람 출력 활성화, 노이즈 억제(ANS) 모드',
      ne107: '-',
      medi: '와류 유량 태그의 스파이크/노이즈 증가 시 SSP 진단 상태와 교차 확인',
      source: 'Yokogawa 공식 제품페이지 · GS01F06A00-01EN',
      verified: true,
    },
    {
      cat: 'flow', vendor: 'KROHNE', model: 'OPTIMASS(MFC 400) / OPTIFLUX',
      func: 'OPTICHECK 내장 진단 + 인시투 검증',
      detects: '센서·전자부 이상, 측정 불확도 증가, 허용 외 공정 조건, 배선 고장',
      signature: 'MFC 400 스마트 진단이 1분 이내 기기 전체 점검, NE107 상태로 표시(디스플레이 배경색 연동). OPTICHECK 검증 툴은 공정 중단 없이 인라인 헬스체크 + 기기별 검증 리포트. 합격 기준 %값 수치 미확인.',
      setting: '진단 표시 규격(NE107/WIB 2650), 상태 출력 매핑, 검증 주기',
      ne107: '적색 F(신호 무효)/황색 S(사양 이탈)/청색 M(정비 필요)',
      medi: '유량 태그 품질 의심 시 교차 확인',
      source: 'KROHNE OPTICHECK·MFC 400 공식 페이지',
      verified: true,
    },

    // ══════════ 진동 ══════════
    {
      cat: 'vibration', vendor: 'Bently Nevada (Baker Hughes)', model: '3500 시리즈 + 3300 XL 프로브 (API 670)',
      func: 'OK 리밋 감시 / NOT OK 판정 (트랜스듀서 건전성)',
      detects: '근접 프로브·익스텐션 케이블·Proximitor 단선/단락, 프로브 갭 이탈 (측정값 유효성)',
      signature: '채널 갭 전압이 상/하 OK 리밋을 벗어나면 NOT OK — OK LED 소등, 채널 알람 무효화, OK 릴레이 소자. 복귀는 리밋 내 30초 유지 필요(Timed OK Channel Defeat — 간헐 결선 불량 오트립 방지). 갭 전압 정상범위 통설 -9~-11 VDC(권장 센터 -10 VDC, 프로브 선형범위 약 -2~-18 VDC의 중심) — 채널 타입별 공식 기본값은 원문 미확인. 3300 XL 8mm 감도 7.87 V/mm ±10% (공식 데이터시트).',
      setting: 'Rack Configuration SW에서 채널별 OK 리밋·Alert/Danger 셋포인트·Timed OK Defeat, 설치 시 갭 약 -10 VDC 조정',
      ne107: '-',
      medi: '진동값이 갑자기 0 근처로 붕괴하면 설비 정상화가 아니라 프로브/케이블 먼저 의심 — 계기 건전성 진단이 노이즈 붕괴로 검출',
      source: 'Bently 3500 매뉴얼(2차 경유) · 3300 XL 데이터시트(공식) — 갭 전압 수치는 요확인',
      verified: false,
    },
    {
      cat: 'vibration', vendor: 'SKF', model: '진동 감시 제품군 (Machine Condition Advisor 등)',
      func: 'ISO 10816-3 기반 Alert/Danger 경보',
      detects: '기계 전체 진동 심각도(속도 RMS), 베어링 상태(엔벨로프 가속도) 악화',
      signature: 'ISO 10816-3 존 기준으로 평가 — 속도 0.7~65.0 mm/s RMS 범위에서 Alert/Danger 표시. 업계 통례: Alert=존 B/C 경계, Danger=존 C/D 경계. SKF 고유 기본값 수치 미확인.',
      setting: '기계 그룹/지지 유형(ISO 클래스), Alert·Danger 한계, 베이스라인 상대 경보',
      ne107: '-',
      medi: '트렌드 분석에서 진동 태그 한계선으로 활용',
      source: 'SKF 데이터시트(2차 경유) — 요확인',
      verified: false,
    },
    {
      cat: 'standard', vendor: '표준 (ISO)', model: 'ISO 10816-3 / 20816-3 (15 kW 초과 산업 기계)',
      func: '케이싱 진동 속도 평가 존 (A/B/C/D)',
      detects: '불평형·미스얼라인먼트·풀림 등에 의한 광대역 진동 심각도 (RMS velocity, 10~1000 Hz)',
      signature: '존 A(신품)/B(장기운전 허용)/C(단기 허용·조사 필요)/D(손상 위험). 2차 출처 다수 일치 존 경계(mm/s RMS): Group 1(>300 kW) 강성지지 A/B 2.3·B/C 4.5·C/D 7.1, 유연지지 3.5/7.1/11.0 · Group 2(15~300 kW) 강성 1.4/2.8/4.5, 유연 2.3/4.5/7.1. (표준 원문 직접 열람 불가 — 적용 전 원문 확인)',
      setting: '경보 통례: Alert=존 B/C 경계 부근, Trip=존 C/D 경계 부근 — 표준은 베이스라인 기반 설정 병용 권고',
      ne107: '-',
      medi: '트렌드 분석에서 진동 태그에 존 경계를 한계선으로 설정해 감시',
      source: 'ISO 10816-3/20816-3 (존 경계값은 2차 출처 교차 확인 — 요확인)',
      verified: false,
    },

    // ══════════ 전기/계전기 ══════════
    {
      cat: 'electrical', vendor: 'ABB', model: 'Relion REM615/620 — MPTTR (49M)',
      func: '모터 열과부하 보호 + 재기동 억제',
      detects: '지속 과부하·빈번한 기동에 의한 권선 과열 (thermal level 상승) — 트립 전 선행 경보',
      signature: '전류 기반 열 모델로 thermal level(%)을 연속 연산 — 알람 한계 도달 시 경보, 100%에서 49 트립, 냉각될 때까지 재기동 억제. 공식 파라미터 범위: Alarm thermal value 50.0~100.0%, Restart thermal value 20.0~80.0%, Overload factor 1.00~1.20, 시간상수 80~4000 s. 공장 기본값 수치 미확인. Emergency start 시 10분간 억제 무시 가능.',
      setting: 'Alarm/Restart thermal value, 시간상수(정상/기동), 과부하 계수, 가중 계수 p',
      ne107: '-',
      medi: '열용량(THL) 태그를 수집하면 트립 전 상승을 자동 감시 — M-401 데모와 동일',
      source: 'ABB techdoc (REM620 Product Guide MPTTR · REX640 Technical Manual)',
      verified: true,
    },
    {
      cat: 'electrical', vendor: 'GE Vernova (Multilin)', model: '469 / 869 (모터 관리 릴레이)',
      func: 'Thermal Capacity Used(TCU) 경보·트립 (49)',
      detects: '과부하·불평형·기동 반복에 의한 열용량 소진 — 절연 과열 임박',
      signature: '과부하 곡선·불평형 바이어스·냉각 시간상수·RTD 바이어스로 구성된 열 모델이 TCU(%)를 0.1초마다 갱신 — 100% 도달 시 트립. Thermal Capacity Alarm은 임박한 과부하 트립의 사전 경고(469 매뉴얼 명시). 알람 레벨 공장 기본값 수치 미확인 (현장 통례 75~85% 설은 문서 미확인).',
      setting: 'TC Alarm 레벨(% used)·래치, 과부하 곡선, 냉각 시간상수, Start Inhibit(잔여 TCU 기반)',
      ne107: '-',
      medi: 'TCU 태그 수집 시 트립 선행 감시 가능 — 채터링/기동빈발 진단과 연계',
      source: 'GE 469 Instruction Manual (공식)',
      verified: true,
    },
    {
      cat: 'electrical', vendor: 'Schneider Electric', model: 'Sepam 20/40/60/80 — 49RMS',
      func: '열적 과부하 보호 (RMS 전류 열용량 연산)',
      detects: '과부하에 의한 권선 열상승(% of rated thermal capacity) 초과',
      signature: 'RMS 전류로 연산한 열상승 E(%)를 두 셋포인트와 비교 — ES1(알람) 도달 시 경보, ES2(트립) 도달 시 트립. 설정 범위 둘 다 50~300%. 세팅 가이드 통례: 운전조건 불명 시 ES1=90%. 정상 1.05·Ib 흡수 시 열상승 연산값 110% 도달(ES2≈100~110% 설정 근거). 공장 기본값 수치 미확인.',
      setting: 'ES1(알람)/ES2(트립), 가열·냉각 시간상수, Ib(기준 전류)',
      ne107: '-',
      medi: '열상승 % 태그 수집 시 트립 선행 감시',
      source: 'Schneider Sepam 49RMS Data Bulletin (공식) · SE FAQ',
      verified: true,
    },
    {
      cat: 'electrical', vendor: 'Siemens', model: 'SIPROTEC 5 — 7SK82/85 (모터 보호)',
      func: '49 고정자·회전자 열과부하 + 66/49R 재기동 억제',
      detects: '고정자/회전자 과열, 기동 반복에 의한 회전자 열한계 초과, 기동 시간 초과·로드 잼',
      signature: '열 레플리카가 고정자·회전자 온도 상당치를 연산 — 재기동 억제는 ① 열 스테이지(지금 기동하면 회전자 열한계 초과로 계산되면 기동 금지) ② 카운터 스테이지(cold/warm 기동 횟수 제한). 열 경보 단계 공장 기본값 수치 미확인.',
      setting: 'K-계수(허용 연속전류), 시간상수, 열 경보 단계(%), 기동 횟수 한계, 재기동 대기시간',
      ne107: '-',
      medi: '기동 빈발(66) 진단과 연계 — 기동 횟수·열용량 태그 수집 권장',
      source: 'Siemens 7SK82 공식 페이지 · SIPROTEC 5 매뉴얼 (공식)',
      verified: true,
    },

    // ══════════ 변압기 (표준) ══════════
    {
      cat: 'transformer', vendor: '표준 (IEEE)', model: 'IEEE C57.104 (2019/2008) — DGA 해석',
      func: '용존가스분석(DGA) 상태 판정',
      detects: '부분방전·열적 고장·아크에 의한 용존가스(H₂, CH₄, C₂H₂, C₂H₄, C₂H₆, CO) 증가',
      signature: '2019판: 150만+ 건 통계 기반 Table 1(90분위)/Table 2(95분위)로 Status 1~3 판정 — 한계는 O₂/N₂ 비(밀폐/개방형)와 연령별로 가스마다 다름. 2019판 가스별 ppm 원문 미확인. 참고: 2차 출처들이 "Status 1"로 인용하는 H₂≤100, CH₄≤120, C₂H₂≤1, C₂H₄≤50, C₂H₆≤65, CO≤350 ppm은 2008판 Condition 1 표와 동일 — 판 구분 주의.',
      setting: '온라인 DGA 모니터 경보: Status 경계 + 가스 증가율(rate-of-change)을 사이트 기준으로 설정',
      ne107: '-',
      medi: 'H₂ 등 온라인 DGA 태그를 수집하면 TR 클래스 진단(TR-OIL 등)과 함께 감시 가능',
      source: 'IEEE C57.104 (2019 원문 미확인 — 2차 출처 교차, 요확인)',
      verified: false,
    },
    {
      cat: 'transformer', vendor: '표준 (IEEE)', model: 'IEEE C57.91 — 변압기 부하 가이드',
      func: '유온(top-oil)·최고점(hot-spot) 온도 한계',
      detects: '과부하·냉각 이상에 의한 온도 상승 → 절연지 열화 가속',
      signature: '65°C 권선온도상승 설계의 기준 hot-spot 110°C(55°C 설계는 95°C) — 110°C에서 6°C 초과마다 절연 수명 대략 절반. top-oil 105°C 초과 시 오일 팽창으로 압력방출장치 동작·유출 가능성 명시. 정상 절연 수명 기준 180,000시간(2011판, 배전 기준). 부하 4단계별 온도 한계표는 원문 미확인.',
      setting: '예지보전 경보 통례: top-oil 고경보 105°C 이하 여유값, hot-spot(WTI) 경보 110°C 부근 — 사이트별 설정',
      ne107: '-',
      medi: 'TR 클래스의 부하 보정 유온상승 잔차(cool_residual)가 냉각 열화를 한계 도달 전에 선행 검출',
      source: 'IEEE C57.91 (원문 직접 미확인 — 2차 출처 교차, 요확인)',
      verified: false,
    },
  ];

  // 공식 문서/매뉴얼 다운로드 링크 (func 키) — 세션 환경에선 다운로드가 차단되어도
  // 사용자 PC 브라우저에서는 바로 열림. 미러(2차) 출처는 해당 항목 verified:false와 짝.
  const DOC_URLS = {
    'SPM 통계공정감시 / 임펄스라인 막힘 검출 (Plugged Impulse Line)': 'https://www.emerson.com/documents/automation/technical-note-plugged-impulse-line-detection-rosemount-3051s-advanced-diagnostics-en-us-4232882.pdf',
    'Power Advisory / 루프 건전성 진단': 'https://www.emerson.com/documents/automation/flyer-rosemount-3051-loop-integrity-diagnostic-en-5349108.pdf',
    'ILBD (임펄스라인 막힘 진단)': 'https://web-material3.yokogawa.com/TI01C25A31-01E.pdf',
    'Heat Trace Monitoring (플랜지 온도 진단)': 'https://www.yokogawa.com/us/library/resources/yokogawa-technical-reports/advanced-diagnostic-functions-of-ejx-series-differential-pressure-pressure-transmitters/',
    'PILD (임펄스라인 막힘 검출)': 'https://search.abb.com/library/Download.aspx?DocumentID=TD%2FP-SERIES_PILD-EN&LanguageCode=en&Action=Launch',
    'Heartbeat Technology (Verification + SSD + Loop/Process 진단)': 'https://bdih-download.endress.com/files/DLA/005056A500261EDEAF81E51497A5662A/SD02525PEN_0323-00.pdf',
    'PILD (임펄스라인 막힘 검출, 통계 모델·PILD factor)': 'https://prod-edam.honeywell.com/content/dam/honeywell-edam/pmt/hps/vault/support/Documents/anonymous/pmt-hps-34-st-25-38-st800-hartde.pdf',
    'NE107 진단 — 한계 감시·이벤트 카운터·트렌드 로그': 'https://cache.industry.siemens.com/dl/files/247/109954247/att_1264010/v1/A5E44914141en_P320P420_SM_en-US.pdf',
    'HART 진단 — 교정/서비스 타이머·min/max 포인터·한계 감시': 'https://cache.industry.siemens.com/dl/files/649/81254649/att_99492/v1/A5E00047092-09en_DS3_HART_Ex_OI_en-US.pdf',
    '고급 진단 — 압력 주파수 지표·표준편차 진단': 'https://us.azbil.com/uploadedSpecs/CM2-GTX100-2005.pdf',
    'Sensor Drift Alert (센서 드리프트 경보)': 'https://www.emerson.com/documents/automation/product-data-sheet-rosemount-3144p-temperature-transmitter-en-73128.pdf',
    'Hot Backup + 열전대 열화 진단': 'https://www.emerson.com/documents/automation/product-data-sheet-rosemount-3144p-temperature-transmitter-en-73128.pdf',
    '센서 백업 + 센서 드리프트 감지': 'https://web-material3.yokogawa.com/GS01C50G01-01EN.pdf',
    '센서 드리프트 감시 + 센서 이중화': 'https://new.abb.com/products/measurement-products/temperature/temperature-transmitters/head-mount-transmitters/tth300',
    '드리프트/편차 감시 + 센서 백업 + 부식 감지': 'https://bdih-download.endress.com/file/e2ba15e25aed4e6cc6e369f66cca69ff/BA01028TEN_2624-00.pdf',
    '센서 드리프트 감지 + 부식 감지': 'https://portal.endress.com/wa001/dla/5001099/5274/000/00/BA01801TEN_0117.pdf',
    '센서 드리프트 감지 + 이중 센서 리던던시': 'https://www.wika.com/en-us/t32_xs.WIKA',
    '센서 리던던시 + 드리프트 감지': 'https://cache.industry.siemens.com/dl/files/594/99592594/att_55073/v1/A5E01018688-03en_TH400_OI_en-US.pdf',
    'Travel Deviation Alert (트래블 편차 경보)': 'https://www.emerson.com/documents/automation/instruction-manual-fieldvue-dvc6200-hw2-digital-valve-controller-en-en-11382598.pdf',
    'Supply Pressure Lo Alert (공급압 저하 경보)': 'https://www.emerson.com/documents/automation/instruction-manual-fieldvue-dvc6200-hw2-digital-valve-controller-en-en-11382598.pdf',
    'Cycle Counter / Travel Accumulator': 'https://www.emerson.com/documents/automation/instruction-manual-fieldvue-dvc6200-hw2-digital-valve-controller-en-en-11382598.pdf',
    'PST (부분행정시험)': 'https://www.emerson.com/documents/automation/im-supplement-fieldvue-dvc6200-sis-digital-valve-controller-pst-calibration-testing-using-valvelink-software-en-11744890.pdf',
    'Load Factor(부하율) + 스틱션 온라인 진단': 'https://www.valmet.com/globalassets/sharepoint/imported/nd9000f_users_guide.pdf',
    'EXPERTplus 내장 밸브 진단 (데드밴드·스텝응답·구동신호)': 'https://www.samsongroup.com/document/e83893en.pdf',
    '마찰·압력 진단 + 사이클/트래블 누적 카운터': 'https://www.flowserve.com/products/products-catalog/actuators-instrumentation/positioners/digital-positioners-logix-3400md/',
    '스트로크/방향전환 카운터 + 데드밴드 자동 적응': 'https://support.industry.siemens.com/cs/attachments/28951425/PS2_PAR_DIAG_r1.pdf',
    '토크 프로파일 + 모터 상태 진단': 'https://www.flowserve.com/en/products/actuation-instrumentation/electric-actuators/multi-turn-electric-actuators/limitorque-mx/',
    'Smart Meter Verification (인시투 계기 검증)': 'https://www.emerson.com/documents/automation/white-paper-using-structural-integrity-meter-verification-to-track-corrosion-in-coriolis-flowmeters-micro-motion-en-66236.pdf',
    'Heartbeat Verification (추적성 검증)': 'https://portal.endress.com/dla/5001055/5641/000/00/SD01643DEN_0116.pdf',
    'Heartbeat Verification': 'https://portal.endress.com/wa001/dla/5001079/0011/000/00/SD01847DEN_0116.pdf',
    'SSP 자기진단 (Spectral Signal Processing)': 'https://web-material3.yokogawa.com/GS01F06A00-01EN.pdf',
    'OPTICHECK 내장 진단 + 인시투 검증': 'https://www.krohne.com/en-us/technologies/opticheck-technology-built-in',
    'OK 리밋 감시 / NOT OK 판정 (트랜스듀서 건전성)': 'https://dam.bakerhughes.com/m/23d2a1de24360b13/original/3300-XL-8mm-Proximity-Transducer-System-Datasheet-141194-pdf.pdf',
    'ISO 10816-3 기반 Alert/Danger 경보': 'https://assets.tequipment.net/assets/1/26/SKF_Condition_Monitoring_Essentials_Data_Sheet.pdf',
    '케이싱 진동 속도 평가 존 (A/B/C/D)': 'https://dspanalytic.com/en/vibrations/understanding-the-iso-10816-3-vibration-severity-table/',
    '모터 열과부하 보호 + 재기동 억제': 'https://techdoc.relays.protection-control.abb/r/REM620-Product-Guide/2.0-FP1-IEC/en-US/Thermal-overload-protection-for-motors-MPTTR',
    'Thermal Capacity Used(TCU) 경보·트립 (49)': 'http://www.gegridsolutions.com/products/manuals/469/469man-a7.pdf',
    '열적 과부하 보호 (RMS 전류 열용량 연산)': 'https://download.schneider-electric.com/files?p_Doc_Ref=3000DB0811&p_File_Name=3000DB0811+SEPAM+49+RMS.pdf&p_enDocType=Data+Bulletin',
    '49 고정자·회전자 열과부하 + 66/49R 재기동 억제': 'https://cache.industry.siemens.com/dl/files/390/109742390/att_927048/v1/SIP5_7SK82-85_V07.50_Manual_C024-6_en.pdf',
    '용존가스분석(DGA) 상태 판정': 'https://powerprognosis.com/ieee-c57-104-2019-vs-2008-what-changed-why-it-matters-for-transformer-dga/',
    '유온(top-oil)·최고점(hot-spot) 온도 한계': 'https://www.hvassets.com/en/post/ieee-c57-91-2025-guide-for-loading-transformers',
  };
  for (const it of ITEMS) {
    if (!it.url && DOC_URLS[it.func]) it.url = DOC_URLS[it.func];
  }

  function search(items, q, cat, vendor) {
    const qq = (q || '').trim().toLowerCase();
    return items.filter(it =>
      (!cat || it.cat === cat) &&
      (!vendor || it.vendor === vendor) &&
      (!qq || [it.vendor, it.model, it.func, it.detects, it.signature, it.setting].join(' ').toLowerCase().includes(qq)));
  }

  function vendors(items) {
    return [...new Set(items.map(i => i.vendor))].sort();
  }

  return { CATS, ITEMS, search, vendors };
});
